### ISSUE TITLE
PHP FPM port 9000 not working when published on Heroku

### ISSUE THREAD

**Issue by devkinggod** [steffanhalv/servewp#1]
Hello @steffanhalv .

I am developing a project with React.js and I am in need to serve wordpress inside my project.

I know this project used Express framework and the way I have served wordpress is embedding this Express server inside my React.js project.

It's working fine on local environment and but if I publish this React.js project on heroku, serving wordpress stopped.

I think the PHP FPM port is the problem. 9000 is working fine on local environment but it's not working on heroku.

This is the log if I try to serve wordpress on hosted website.
```
new Responder 1 for /blog/index.php
send BEGIN_REQUEST
send PARAMS
send PARAMS
send STDIN
at=error code=H12 desc="Request timeout" method=GET path="/blog/" host=sheltered-lowlands-72820.herokuapp.com request_id=a7a81b31-22f1-456c-b278-71bea691bd05 fwd="182.173.120.193" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
```

I would be appreciate any help from you. Thanks in advance.

**Comment by steffanhalv** [comment]
Hello Daniel.

This method is using both NodeJS and PHP.
In Heroku I think you have to choose between one of them, so I would instead only use this for development purpose and use a full PHP setup on Heroku.

Else you could setup a linux server on Google Cloud platform for Amazon AWS / Microsoft Azure.

I dont think this will work on Heroku, I'm sorry.

**Comment by devkinggod** [comment]
Hello @steffanhalv . Thanks for your reply.

You helped me a lot.

**Comment by devkinggod** [comment]
Hello @steffanhalv . Do you have experience deploying this project using Docker?

I think it is possible to deploy Linux server on heroku using Docker.

**Comment by devkinggod** [comment]
When I deply on docker and trying serve WordPress, this is the log.
```
new Responder 1 for /blog/index.php
send BEGIN_REQUEST
send PARAMS
send PARAMS
send STDIN
true
Error: connect ECONNREFUSED 127.0.0.1:9000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```
Do you have any idea why? I would appreciate any advise. Thanks
